# Generated by Django 3.2.4 on 2022-06-11 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20220611_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.category'),
        ),
    ]
