# Generated by Django 3.2.4 on 2022-06-11 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_todolist_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['-due_date']},
        ),
    ]
